# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcpu', models.FloatField()),
                ('pmem', models.FloatField()),
                ('pload', models.FloatField()),
                ('vcpu', models.FloatField()),
                ('vmem', models.FloatField()),
                ('tcptv', models.FloatField()),
                ('tcpnum', models.IntegerField()),
                ('tcptime', models.IntegerField()),
                ('udptv', models.FloatField()),
                ('udpnum', models.IntegerField()),
                ('udptime', models.IntegerField()),
                ('icmptv', models.FloatField()),
                ('icmpnum', models.IntegerField()),
                ('icmptime', models.IntegerField()),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
