# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20160502_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='icmpnum',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='icmptime',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='tcpnum',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='tcptime',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='tcptv',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='udpnum',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='udptime',
        ),
    ]
