# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_auto_20160508_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threshold',
            old_name='udptv',
            new_name='sshtv',
        ),
        migrations.AddField(
            model_name='threshold',
            name='icmpntv',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
